# Generated by Django 4.1.7 on 2023-03-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accnumber', models.CharField(max_length=1000)),
                ('IFSC', models.CharField(max_length=1000)),
                ('accholder', models.CharField(max_length=1000)),
            ],
        ),
    ]
